import type {
  UserProfile,
  Contact,
  Event,
  GiftPlan,
  GiftIdea,
  Wishlist,
  WishlistItem,
  GiftHistory,
  Relationship,
  GiftingStyle,
  EventType,
  Priority,
  GiftPlanStatus,
  GiftDirection,
} from '@/lib/types';
import { addDays, formatISO } from 'date-fns';

const now = new Date();
const generateId = () => `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
const generateToken = () => Math.random().toString(36).substr(2, 16);

export function createSeedData() {
  // User Profile
  const user: UserProfile = {
    id: generateId(),
    name: 'Alex Morgan',
    defaultBudgetMin: 25,
    defaultBudgetMax: 150,
    giftingStyle: 'thoughtful',
    topRelationships: ['family', 'friend', 'coworker'],
    createdAt: formatISO(addDays(now, -60)),
  };

  // Contacts (10)
  const contacts: Contact[] = [
    {
      id: 'contact-1',
      name: 'Sarah Chen',
      relationship: 'friend',
      tags: ['best-friend', 'college'],
      interests: ['photography', 'cooking', 'books'],
      notes: 'Loves trying new recipes',
      createdAt: formatISO(addDays(now, -50)),
      updatedAt: formatISO(addDays(now, -10)),
    },
    {
      id: 'contact-2',
      name: 'Michael Johnson',
      relationship: 'family',
      tags: ['brother'],
      interests: ['technology', 'gaming', 'craft-beer'],
      notes: 'Birthday is important to him',
      createdAt: formatISO(addDays(now, -55)),
      updatedAt: formatISO(addDays(now, -5)),
    },
    {
      id: 'contact-3',
      name: 'Emily Rodriguez',
      relationship: 'friend',
      tags: ['close-friend'],
      interests: ['yoga', 'wellness', 'travel'],
      createdAt: formatISO(addDays(now, -45)),
      updatedAt: formatISO(addDays(now, -15)),
    },
    {
      id: 'contact-4',
      name: 'David Kim',
      relationship: 'coworker',
      tags: ['team-lead'],
      interests: ['coffee', 'management-books', 'running'],
      notes: 'Team lead, keep it professional but thoughtful',
      createdAt: formatISO(addDays(now, -40)),
      updatedAt: formatISO(addDays(now, -8)),
    },
    {
      id: 'contact-5',
      name: 'Jennifer Martinez',
      relationship: 'family',
      tags: ['sister'],
      interests: ['fashion', 'art', 'music'],
      createdAt: formatISO(addDays(now, -52)),
      updatedAt: formatISO(addDays(now, -3)),
    },
    {
      id: 'contact-6',
      name: 'Robert Taylor',
      relationship: 'friend',
      tags: ['gym-buddy'],
      interests: ['fitness', 'nutrition', 'sports'],
      createdAt: formatISO(addDays(now, -38)),
      updatedAt: formatISO(addDays(now, -12)),
    },
    {
      id: 'contact-7',
      name: 'Lisa Wang',
      relationship: 'coworker',
      tags: ['peer'],
      interests: ['productivity', 'tech-gadgets', 'podcasts'],
      createdAt: formatISO(addDays(now, -35)),
      updatedAt: formatISO(addDays(now, -7)),
    },
    {
      id: 'contact-8',
      name: 'James Wilson',
      relationship: 'family',
      tags: ['father'],
      interests: ['gardening', 'history', 'classical-music'],
      notes: 'Appreciates meaningful gifts',
      createdAt: formatISO(addDays(now, -58)),
      updatedAt: formatISO(addDays(now, -2)),
    },
    {
      id: 'contact-9',
      name: 'Olivia Brown',
      relationship: 'friend',
      tags: ['childhood-friend'],
      interests: ['vintage', 'sustainability', 'baking'],
      createdAt: formatISO(addDays(now, -48)),
      updatedAt: formatISO(addDays(now, -6)),
    },
    {
      id: 'contact-10',
      name: 'Thomas Anderson',
      relationship: 'coworker',
      tags: ['mentor'],
      interests: ['leadership', 'philosophy', 'wine'],
      notes: 'Mentor figure, formal but personal',
      createdAt: formatISO(addDays(now, -42)),
      updatedAt: formatISO(addDays(now, -4)),
    },
  ];

  // Events (15 across next 90 days)
  const events: Event[] = [
    {
      id: 'event-1',
      contactId: 'contact-1',
      type: 'birthday',
      title: "Sarah's Birthday",
      dateISO: formatISO(addDays(now, 12)),
      recurrence: 'yearly',
      reminderOffsetsDays: [30, 14, 7, 1],
      createdAt: formatISO(addDays(now, -20)),
      updatedAt: formatISO(addDays(now, -5)),
    },
    {
      id: 'event-2',
      contactId: 'contact-2',
      type: 'birthday',
      title: "Michael's Birthday",
      dateISO: formatISO(addDays(now, 8)),
      recurrence: 'yearly',
      reminderOffsetsDays: [30, 7, 1],
      createdAt: formatISO(addDays(now, -25)),
      updatedAt: formatISO(addDays(now, -3)),
    },
    {
      id: 'event-3',
      contactId: 'contact-5',
      type: 'anniversary',
      title: "Jennifer's Wedding Anniversary",
      dateISO: formatISO(addDays(now, 25)),
      recurrence: 'yearly',
      reminderOffsetsDays: [14, 7],
      createdAt: formatISO(addDays(now, -18)),
      updatedAt: formatISO(addDays(now, -2)),
    },
    {
      id: 'event-4',
      contactId: 'contact-3',
      type: 'birthday',
      title: "Emily's Birthday",
      dateISO: formatISO(addDays(now, 45)),
      recurrence: 'yearly',
      reminderOffsetsDays: [30, 14, 7],
      createdAt: formatISO(addDays(now, -15)),
      updatedAt: formatISO(addDays(now, -8)),
    },
    {
      id: 'event-5',
      contactId: 'contact-4',
      type: 'custom',
      title: "David's Promotion Celebration",
      dateISO: formatISO(addDays(now, 3)),
      recurrence: 'none',
      reminderOffsetsDays: [1],
      createdAt: formatISO(addDays(now, -2)),
      updatedAt: formatISO(addDays(now, -1)),
    },
    {
      id: 'event-6',
      contactId: 'contact-6',
      type: 'birthday',
      title: "Robert's Birthday",
      dateISO: formatISO(addDays(now, 60)),
      recurrence: 'yearly',
      reminderOffsetsDays: [30, 14, 7],
      createdAt: formatISO(addDays(now, -12)),
      updatedAt: formatISO(addDays(now, -6)),
    },
    {
      id: 'event-7',
      contactId: 'contact-7',
      type: 'custom',
      title: "Lisa's Housewarming",
      dateISO: formatISO(addDays(now, 18)),
      recurrence: 'none',
      reminderOffsetsDays: [7, 1],
      createdAt: formatISO(addDays(now, -10)),
      updatedAt: formatISO(addDays(now, -4)),
    },
    {
      id: 'event-8',
      contactId: 'contact-8',
      type: 'birthday',
      title: "James's Birthday",
      dateISO: formatISO(addDays(now, 75)),
      recurrence: 'yearly',
      reminderOffsetsDays: [30, 14, 7, 1],
      createdAt: formatISO(addDays(now, -30)),
      updatedAt: formatISO(addDays(now, -1)),
    },
    {
      id: 'event-9',
      contactId: 'contact-9',
      type: 'birthday',
      title: "Olivia's Birthday",
      dateISO: formatISO(addDays(now, 35)),
      recurrence: 'yearly',
      reminderOffsetsDays: [30, 14, 7],
      createdAt: formatISO(addDays(now, -22)),
      updatedAt: formatISO(addDays(now, -7)),
    },
    {
      id: 'event-10',
      contactId: 'contact-10',
      type: 'custom',
      title: "Thomas's Retirement Party",
      dateISO: formatISO(addDays(now, 50)),
      recurrence: 'none',
      reminderOffsetsDays: [30, 14, 7],
      createdAt: formatISO(addDays(now, -16)),
      updatedAt: formatISO(addDays(now, -9)),
    },
    {
      id: 'event-11',
      type: 'holiday',
      title: 'Valentine\'s Day',
      dateISO: formatISO(addDays(now, 28)),
      recurrence: 'yearly',
      reminderOffsetsDays: [14, 7],
      createdAt: formatISO(addDays(now, -14)),
      updatedAt: formatISO(addDays(now, -11)),
    },
    {
      id: 'event-12',
      contactId: 'contact-1',
      type: 'custom',
      title: "Sarah's Graduation",
      dateISO: formatISO(addDays(now, 65)),
      recurrence: 'none',
      reminderOffsetsDays: [30, 14],
      createdAt: formatISO(addDays(now, -13)),
      updatedAt: formatISO(addDays(now, -10)),
    },
    {
      id: 'event-13',
      contactId: 'contact-2',
      type: 'custom',
      title: "Michael's New Baby",
      dateISO: formatISO(addDays(now, 20)),
      recurrence: 'none',
      reminderOffsetsDays: [7, 1],
      createdAt: formatISO(addDays(now, -9)),
      updatedAt: formatISO(addDays(now, -5)),
    },
    {
      id: 'event-14',
      contactId: 'contact-5',
      type: 'birthday',
      title: "Jennifer's Birthday",
      dateISO: formatISO(addDays(now, 82)),
      recurrence: 'yearly',
      reminderOffsetsDays: [30, 14, 7],
      createdAt: formatISO(addDays(now, -24)),
      updatedAt: formatISO(addDays(now, -2)),
    },
    {
      id: 'event-15',
      contactId: 'contact-4',
      type: 'anniversary',
      title: "David's Work Anniversary",
      dateISO: formatISO(addDays(now, 42)),
      recurrence: 'yearly',
      reminderOffsetsDays: [7],
      createdAt: formatISO(addDays(now, -11)),
      updatedAt: formatISO(addDays(now, -8)),
    },
  ];

  // Gift Plans (8)
  const plans: GiftPlan[] = [
    {
      id: 'plan-1',
      contactId: 'contact-1',
      eventId: 'event-1',
      budgetMin: 50,
      budgetMax: 100,
      status: 'planned',
      ideas: [
        { id: 'idea-1', title: 'Cookbook Collection', priceMin: 45, priceMax: 60, priority: 'high' as Priority },
        { id: 'idea-2', title: 'Camera Lens Filter', priceMin: 30, priceMax: 50, priority: 'med' as Priority },
      ],
      createdAt: formatISO(addDays(now, -15)),
      updatedAt: formatISO(addDays(now, -5)),
    },
    {
      id: 'plan-2',
      contactId: 'contact-2',
      eventId: 'event-2',
      budgetMin: 75,
      budgetMax: 150,
      status: 'purchased',
      ideas: [
        { id: 'idea-3', title: 'Wireless Gaming Mouse', priceMin: 80, priceMax: 120, priority: 'high' as Priority },
        { id: 'idea-4', title: 'Craft Beer Gift Set', priceMin: 40, priceMax: 60, priority: 'med' as Priority },
      ],
      purchasedTotal: 95,
      createdAt: formatISO(addDays(now, -20)),
      updatedAt: formatISO(addDays(now, -1)),
    },
    {
      id: 'plan-3',
      contactId: 'contact-5',
      eventId: 'event-3',
      budgetMin: 100,
      budgetMax: 200,
      status: 'given',
      ideas: [
        { id: 'idea-5', title: 'Spa Day Gift Certificate', priceMin: 150, priceMax: 200, priority: 'high' as Priority },
      ],
      purchasedTotal: 175,
      createdAt: formatISO(addDays(now, -18)),
      updatedAt: formatISO(addDays(now, -7)),
    },
    {
      id: 'plan-4',
      contactId: 'contact-4',
      eventId: 'event-5',
      budgetMin: 25,
      budgetMax: 50,
      status: 'planned',
      ideas: [
        { id: 'idea-6', title: 'Premium Coffee Beans', priceMin: 25, priceMax: 35, priority: 'high' as Priority },
        { id: 'idea-7', title: 'Leadership Book', priceMin: 15, priceMax: 25, priority: 'low' as Priority },
      ],
      createdAt: formatISO(addDays(now, -2)),
      updatedAt: formatISO(addDays(now, -1)),
    },
    {
      id: 'plan-5',
      contactId: 'contact-3',
      eventId: 'event-4',
      budgetMin: 50,
      budgetMax: 100,
      status: 'planned',
      ideas: [
        { id: 'idea-8', title: 'Yoga Mat Set', priceMin: 40, priceMax: 60, priority: 'high' as Priority },
        { id: 'idea-9', title: 'Travel Journal', priceMin: 20, priceMax: 30, priority: 'med' as Priority },
      ],
      createdAt: formatISO(addDays(now, -10)),
      updatedAt: formatISO(addDays(now, -8)),
    },
    {
      id: 'plan-6',
      contactId: 'contact-7',
      eventId: 'event-7',
      budgetMin: 30,
      budgetMax: 75,
      status: 'purchased',
      ideas: [
        { id: 'idea-10', title: 'Smart Home Device', priceMin: 50, priceMax: 70, priority: 'high' as Priority },
      ],
      purchasedTotal: 65,
      createdAt: formatISO(addDays(now, -8)),
      updatedAt: formatISO(addDays(now, -3)),
    },
    {
      id: 'plan-7',
      contactId: 'contact-8',
      budgetMin: 50,
      budgetMax: 100,
      status: 'planned',
      ideas: [
        { id: 'idea-11', title: 'Garden Tool Set', priceMin: 45, priceMax: 65, priority: 'high' as Priority },
      ],
      createdAt: formatISO(addDays(now, -25)),
      updatedAt: formatISO(addDays(now, -2)),
    },
    {
      id: 'plan-8',
      contactId: 'contact-10',
      eventId: 'event-10',
      budgetMin: 100,
      budgetMax: 200,
      status: 'planned',
      ideas: [
        { id: 'idea-12', title: 'Wine Collection', priceMin: 120, priceMax: 180, priority: 'high' as Priority },
        { id: 'idea-13', title: 'Leather Portfolio', priceMin: 80, priceMax: 120, priority: 'med' as Priority },
      ],
      createdAt: formatISO(addDays(now, -14)),
      updatedAt: formatISO(addDays(now, -9)),
    },
  ];

  // Wishlists (3)
  const wishlist1: Wishlist = {
    id: 'wishlist-1',
    ownerContactId: 'contact-1',
    title: "Sarah's Wishlist",
    description: 'Things I would love to receive',
    shareToken: generateToken(),
    createdAt: formatISO(addDays(now, -30)),
    updatedAt: formatISO(addDays(now, -5)),
  };

  const wishlist2: Wishlist = {
    id: 'wishlist-2',
    ownerContactId: 'contact-5',
    title: "Jennifer's Birthday Ideas",
    description: 'Gift ideas for my birthday',
    shareToken: generateToken(),
    createdAt: formatISO(addDays(now, -25)),
    updatedAt: formatISO(addDays(now, -3)),
  };

  const wishlist3: Wishlist = {
    id: 'wishlist-3',
    ownerContactId: 'contact-3',
    title: "Emily's Wishlist",
    shareToken: generateToken(),
    createdAt: formatISO(addDays(now, -20)),
    updatedAt: formatISO(addDays(now, -10)),
  };

  const wishlists: Wishlist[] = [wishlist1, wishlist2, wishlist3];

  // Wishlist Items (20 total)
  const wishlistItems: WishlistItem[] = [
    { id: 'item-1', wishlistId: 'wishlist-1', title: 'Professional Camera Strap', priceMin: 40, priceMax: 60, priority: 'high' as Priority },
    { id: 'item-2', wishlistId: 'wishlist-1', title: 'Recipe Book: Modern Italian', priceMin: 25, priceMax: 35, priority: 'med' as Priority },
    { id: 'item-3', wishlistId: 'wishlist-1', title: 'Kitchen Knife Set', priceMin: 80, priceMax: 120, priority: 'high' as Priority },
    { id: 'item-4', wishlistId: 'wishlist-1', title: 'Cookbook Stand', priceMin: 20, priceMax: 30, priority: 'low' as Priority },
    { id: 'item-5', wishlistId: 'wishlist-1', title: 'Photography Lighting Kit', priceMin: 100, priceMax: 150, priority: 'med' as Priority },
    { id: 'item-6', wishlistId: 'wishlist-1', title: 'Book: "The Art of Photography"', priceMin: 30, priceMax: 45, priority: 'med' as Priority },
    { id: 'item-7', wishlistId: 'wishlist-2', title: 'Designer Handbag', priceMin: 200, priceMax: 300, priority: 'high' as Priority },
    { id: 'item-8', wishlistId: 'wishlist-2', title: 'Art Print Collection', priceMin: 50, priceMax: 80, priority: 'med' as Priority },
    { id: 'item-9', wishlistId: 'wishlist-2', title: 'Wireless Headphones', priceMin: 150, priceMax: 200, priority: 'high' as Priority },
    { id: 'item-10', wishlistId: 'wishlist-2', title: 'Concert Tickets', priceMin: 100, priceMax: 200, priority: 'high' as Priority },
    { id: 'item-11', wishlistId: 'wishlist-2', title: 'Fashion Magazine Subscription', priceMin: 25, priceMax: 40, priority: 'low' as Priority },
    { id: 'item-12', wishlistId: 'wishlist-2', title: 'Perfume Set', priceMin: 60, priceMax: 90, priority: 'med' as Priority },
    { id: 'item-13', wishlistId: 'wishlist-3', title: 'Premium Yoga Mat', priceMin: 60, priceMax: 90, priority: 'high' as Priority },
    { id: 'item-14', wishlistId: 'wishlist-3', title: 'Meditation App Subscription', priceMin: 50, priceMax: 80, priority: 'med' as Priority },
    { id: 'item-15', wishlistId: 'wishlist-3', title: 'Travel Backpack', priceMin: 120, priceMax: 180, priority: 'high' as Priority },
    { id: 'item-16', wishlistId: 'wishlist-3', title: 'Wellness Journal', priceMin: 20, priceMax: 30, priority: 'low' as Priority },
    { id: 'item-17', wishlistId: 'wishlist-3', title: 'Essential Oils Set', priceMin: 40, priceMax: 60, priority: 'med' as Priority },
    { id: 'item-18', wishlistId: 'wishlist-3', title: 'Fitness Tracker', priceMin: 80, priceMax: 120, priority: 'high' as Priority },
    { id: 'item-19', wishlistId: 'wishlist-3', title: 'Travel Guide Books', priceMin: 30, priceMax: 50, priority: 'low' as Priority },
    { id: 'item-20', wishlistId: 'wishlist-3', title: 'Sustainable Water Bottle', priceMin: 25, priceMax: 40, priority: 'low' as Priority },
  ];

  // Gift History (25 entries)
  const history: GiftHistory[] = [
    { id: 'hist-1', direction: 'given' as GiftDirection, contactId: 'contact-1', eventId: 'event-1', dateISO: formatISO(addDays(now, -365)), amountMin: 50, amountMax: 75, notes: 'Cookbook set', createdAt: formatISO(addDays(now, -360)) },
    { id: 'hist-2', direction: 'given' as GiftDirection, contactId: 'contact-2', dateISO: formatISO(addDays(now, -340)), amountMin: 100, amountMax: 150, notes: 'Gaming headset', createdAt: formatISO(addDays(now, -335)) },
    { id: 'hist-3', direction: 'given' as GiftDirection, contactId: 'contact-5', eventId: 'event-3', dateISO: formatISO(addDays(now, -330)), amountMin: 120, amountMax: 180, notes: 'Jewelry', createdAt: formatISO(addDays(now, -325)) },
    { id: 'hist-4', direction: 'received' as GiftDirection, contactId: 'contact-1', dateISO: formatISO(addDays(now, -320)), amountMin: 75, amountMax: 100, notes: 'Birthday gift', createdAt: formatISO(addDays(now, -315)) },
    { id: 'hist-5', direction: 'given' as GiftDirection, contactId: 'contact-3', dateISO: formatISO(addDays(now, -300)), amountMin: 40, amountMax: 60, notes: 'Yoga accessories', createdAt: formatISO(addDays(now, -295)) },
    { id: 'hist-6', direction: 'given' as GiftDirection, contactId: 'contact-4', dateISO: formatISO(addDays(now, -280)), amountMin: 30, amountMax: 50, notes: 'Coffee subscription', createdAt: formatISO(addDays(now, -275)) },
    { id: 'hist-7', direction: 'received' as GiftDirection, contactId: 'contact-2', dateISO: formatISO(addDays(now, -270)), amountMin: 50, amountMax: 75, notes: 'Holiday gift', createdAt: formatISO(addDays(now, -265)) },
    { id: 'hist-8', direction: 'given' as GiftDirection, contactId: 'contact-6', dateISO: formatISO(addDays(now, -250)), amountMin: 45, amountMax: 70, notes: 'Fitness equipment', createdAt: formatISO(addDays(now, -245)) },
    { id: 'hist-9', direction: 'given' as GiftDirection, contactId: 'contact-7', dateISO: formatISO(addDays(now, -230)), amountMin: 25, amountMax: 40, notes: 'Tech gadget', createdAt: formatISO(addDays(now, -225)) },
    { id: 'hist-10', direction: 'given' as GiftDirection, contactId: 'contact-8', dateISO: formatISO(addDays(now, -220)), amountMin: 60, amountMax: 90, notes: 'Gardening tools', createdAt: formatISO(addDays(now, -215)) },
    { id: 'hist-11', direction: 'received' as GiftDirection, contactId: 'contact-5', dateISO: formatISO(addDays(now, -210)), amountMin: 80, amountMax: 120, notes: 'Anniversary gift', createdAt: formatISO(addDays(now, -205)) },
    { id: 'hist-12', direction: 'given' as GiftDirection, contactId: 'contact-9', dateISO: formatISO(addDays(now, -200)), amountMin: 35, amountMax: 55, notes: 'Vintage items', createdAt: formatISO(addDays(now, -195)) },
    { id: 'hist-13', direction: 'given' as GiftDirection, contactId: 'contact-10', dateISO: formatISO(addDays(now, -180)), amountMin: 100, amountMax: 150, notes: 'Wine collection', createdAt: formatISO(addDays(now, -175)) },
    { id: 'hist-14', direction: 'received' as GiftDirection, contactId: 'contact-3', dateISO: formatISO(addDays(now, -170)), amountMin: 55, amountMax: 85, notes: 'Thank you gift', createdAt: formatISO(addDays(now, -165)) },
    { id: 'hist-15', direction: 'given' as GiftDirection, contactId: 'contact-1', dateISO: formatISO(addDays(now, -150)), amountMin: 70, amountMax: 100, notes: 'Photography equipment', createdAt: formatISO(addDays(now, -145)) },
    { id: 'hist-16', direction: 'given' as GiftDirection, contactId: 'contact-2', dateISO: formatISO(addDays(now, -140)), amountMin: 90, amountMax: 130, notes: 'Gaming console accessory', createdAt: formatISO(addDays(now, -135)) },
    { id: 'hist-17', direction: 'received' as GiftDirection, contactId: 'contact-4', dateISO: formatISO(addDays(now, -130)), amountMin: 40, amountMax: 60, notes: 'Work gift', createdAt: formatISO(addDays(now, -125)) },
    { id: 'hist-18', direction: 'given' as GiftDirection, contactId: 'contact-5', dateISO: formatISO(addDays(now, -120)), amountMin: 110, amountMax: 160, notes: 'Designer item', createdAt: formatISO(addDays(now, -115)) },
    { id: 'hist-19', direction: 'given' as GiftDirection, contactId: 'contact-6', dateISO: formatISO(addDays(now, -100)), amountMin: 50, amountMax: 75, notes: 'Fitness tracker', createdAt: formatISO(addDays(now, -95)) },
    { id: 'hist-20', direction: 'received' as GiftDirection, contactId: 'contact-7', dateISO: formatISO(addDays(now, -90)), amountMin: 35, amountMax: 50, notes: 'Holiday gift', createdAt: formatISO(addDays(now, -85)) },
    { id: 'hist-21', direction: 'given' as GiftDirection, contactId: 'contact-8', dateISO: formatISO(addDays(now, -80)), amountMin: 65, amountMax: 95, notes: 'Book collection', createdAt: formatISO(addDays(now, -75)) },
    { id: 'hist-22', direction: 'given' as GiftDirection, contactId: 'contact-9', dateISO: formatISO(addDays(now, -70)), amountMin: 40, amountMax: 65, notes: 'Sustainable products', createdAt: formatISO(addDays(now, -65)) },
    { id: 'hist-23', direction: 'received' as GiftDirection, contactId: 'contact-10', dateISO: formatISO(addDays(now, -60)), amountMin: 120, amountMax: 180, notes: 'Mentor gift', createdAt: formatISO(addDays(now, -55)) },
    { id: 'hist-24', direction: 'given' as GiftDirection, contactId: 'contact-3', dateISO: formatISO(addDays(now, -50)), amountMin: 55, amountMax: 85, notes: 'Wellness package', createdAt: formatISO(addDays(now, -45)) },
    { id: 'hist-25', direction: 'given' as GiftDirection, contactId: 'contact-1', dateISO: formatISO(addDays(now, -40)), amountMin: 60, amountMax: 90, notes: 'Cookbook collection', createdAt: formatISO(addDays(now, -35)) },
  ];

  return {
    user,
    contacts,
    events,
    plans,
    wishlists,
    wishlistItems,
    history,
  };
}
